--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2026-03-12 20:21:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 283 (class 1259 OID 30192)
-- Name: avaliacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.avaliacoes (
    id bigint NOT NULL,
    pedido_id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    restaurante_id bigint NOT NULL,
    nota integer NOT NULL,
    comentario text,
    criado_em timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT avaliacoes_nota_check CHECK (((nota >= 1) AND (nota <= 5)))
);


--
-- TOC entry 282 (class 1259 OID 30191)
-- Name: avaliacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.avaliacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5350 (class 0 OID 0)
-- Dependencies: 282
-- Name: avaliacoes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.avaliacoes_id_seq OWNED BY public.avaliacoes.id;


--
-- TOC entry 285 (class 1259 OID 30220)
-- Name: carteiras; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carteiras (
    id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    saldo numeric(10,2) DEFAULT 0.00 NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp without time zone
);


--
-- TOC entry 284 (class 1259 OID 30219)
-- Name: carteiras_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.carteiras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5351 (class 0 OID 0)
-- Dependencies: 284
-- Name: carteiras_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.carteiras_id_seq OWNED BY public.carteiras.id;


--
-- TOC entry 216 (class 1259 OID 29480)
-- Name: categorias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categorias (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    descricao text,
    nome character varying(100) NOT NULL,
    ordem_exibicao integer,
    restaurante_id bigint NOT NULL
);


--
-- TOC entry 215 (class 1259 OID 29479)
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 29488)
-- Name: clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    atualizado_em timestamp(6) without time zone,
    cpf character varying(14),
    criado_em timestamp(6) without time zone NOT NULL,
    data_nascimento date,
    email character varying(255),
    nome_completo character varying(255) NOT NULL,
    telefone character varying(20) NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 29487)
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 29496)
-- Name: cupons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cupons (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    codigo character varying(50) NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    desconto_maximo numeric(10,2),
    descricao text,
    limite_uso integer,
    quantidade_usada integer NOT NULL,
    tipo_desconto character varying(20) NOT NULL,
    valido_ate timestamp(6) without time zone NOT NULL,
    valido_de timestamp(6) without time zone NOT NULL,
    valor_desconto numeric(10,2) NOT NULL,
    valor_minimo_pedido numeric(10,2),
    CONSTRAINT cupons_tipo_desconto_check CHECK (((tipo_desconto)::text = ANY ((ARRAY['PERCENTUAL'::character varying, 'VALOR_FIXO'::character varying])::text[])))
);


--
-- TOC entry 219 (class 1259 OID 29495)
-- Name: cupons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 29505)
-- Name: cupons_pedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cupons_pedido (
    id bigint NOT NULL,
    desconto_aplicado numeric(10,2) NOT NULL,
    cupom_id bigint NOT NULL,
    pedido_id bigint NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 29504)
-- Name: cupons_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cupons_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cupons_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 279 (class 1259 OID 30135)
-- Name: descontos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.descontos (
    id bigint NOT NULL,
    produto_id bigint NOT NULL,
    percentual_desconto numeric(5,2) NOT NULL,
    tipo_intervalo character varying(20) NOT NULL,
    data_hora_inicio timestamp without time zone NOT NULL,
    data_hora_fim timestamp without time zone NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_periodo_valido CHECK ((data_hora_fim > data_hora_inicio)),
    CONSTRAINT descontos_percentual_desconto_check CHECK (((percentual_desconto > (0)::numeric) AND (percentual_desconto <= (100)::numeric))),
    CONSTRAINT descontos_tipo_intervalo_check CHECK (((tipo_intervalo)::text = ANY ((ARRAY['DIAS'::character varying, 'HORAS'::character varying])::text[])))
);


--
-- TOC entry 5352 (class 0 OID 0)
-- Dependencies: 279
-- Name: TABLE descontos; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.descontos IS 'Tabela de descontos temporários para produtos';


--
-- TOC entry 5353 (class 0 OID 0)
-- Dependencies: 279
-- Name: COLUMN descontos.percentual_desconto; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.descontos.percentual_desconto IS 'Percentual de desconto aplicado (0.01 a 100.00)';


--
-- TOC entry 5354 (class 0 OID 0)
-- Dependencies: 279
-- Name: COLUMN descontos.tipo_intervalo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.descontos.tipo_intervalo IS 'Tipo de intervalo: DIAS ou HORAS';


--
-- TOC entry 5355 (class 0 OID 0)
-- Dependencies: 279
-- Name: COLUMN descontos.data_hora_inicio; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.descontos.data_hora_inicio IS 'Data e hora de início da vigência do desconto';


--
-- TOC entry 5356 (class 0 OID 0)
-- Dependencies: 279
-- Name: COLUMN descontos.data_hora_fim; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.descontos.data_hora_fim IS 'Data e hora de fim da vigência do desconto';


--
-- TOC entry 5357 (class 0 OID 0)
-- Dependencies: 279
-- Name: COLUMN descontos.ativo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.descontos.ativo IS 'Indica se o desconto está ativo';


--
-- TOC entry 278 (class 1259 OID 30134)
-- Name: descontos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.descontos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5358 (class 0 OID 0)
-- Dependencies: 278
-- Name: descontos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.descontos_id_seq OWNED BY public.descontos.id;


--
-- TOC entry 224 (class 1259 OID 29511)
-- Name: documentos_entregador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documentos_entregador (
    id bigint NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    data_validade date,
    numero_documento character varying(100),
    tipo_documento character varying(50) NOT NULL,
    url_arquivo character varying(500) NOT NULL,
    verificado boolean NOT NULL,
    verificado_em timestamp(6) without time zone,
    verificado_por uuid,
    entregador_id bigint NOT NULL,
    CONSTRAINT documentos_entregador_tipo_documento_check CHECK (((tipo_documento)::text = ANY ((ARRAY['CNH'::character varying, 'RG'::character varying, 'CPF'::character varying, 'COMPROVANTE_RESIDENCIA'::character varying, 'FOTO_VEICULO'::character varying, 'CRLV'::character varying])::text[])))
);


--
-- TOC entry 223 (class 1259 OID 29510)
-- Name: documentos_entregador_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documentos_entregador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_entregador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 291 (class 1259 OID 30272)
-- Name: empresa_modulos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.empresa_modulos (
    id bigint NOT NULL,
    empresa_id bigint NOT NULL,
    modulo character varying(50) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp without time zone NOT NULL
);


--
-- TOC entry 290 (class 1259 OID 30271)
-- Name: empresa_modulos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.empresa_modulos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5359 (class 0 OID 0)
-- Dependencies: 290
-- Name: empresa_modulos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.empresa_modulos_id_seq OWNED BY public.empresa_modulos.id;


--
-- TOC entry 289 (class 1259 OID 30260)
-- Name: empresas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.empresas (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    cnpj character varying(255) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp without time zone NOT NULL,
    atualizado_em timestamp without time zone
);


--
-- TOC entry 288 (class 1259 OID 30259)
-- Name: empresas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.empresas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5360 (class 0 OID 0)
-- Dependencies: 288
-- Name: empresas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.empresas_id_seq OWNED BY public.empresas.id;


--
-- TOC entry 226 (class 1259 OID 29520)
-- Name: enderecos_cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enderecos_cliente (
    id bigint NOT NULL,
    atualizado_em timestamp(6) without time zone,
    bairro character varying(100) NOT NULL,
    cep character varying(10) NOT NULL,
    cidade character varying(100) NOT NULL,
    complemento character varying(255),
    criado_em timestamp(6) without time zone NOT NULL,
    estado character varying(2) NOT NULL,
    latitude numeric(10,8),
    logradouro character varying(255) NOT NULL,
    longitude numeric(11,8),
    numero character varying(20) NOT NULL,
    padrao boolean NOT NULL,
    rotulo character varying(50),
    cliente_id bigint NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 29519)
-- Name: enderecos_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enderecos_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enderecos_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 29528)
-- Name: enderecos_restaurante; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enderecos_restaurante (
    id bigint NOT NULL,
    bairro character varying(100) NOT NULL,
    cep character varying(10) NOT NULL,
    cidade character varying(100) NOT NULL,
    complemento character varying(255),
    estado character varying(2) NOT NULL,
    latitude numeric(10,8),
    logradouro character varying(255) NOT NULL,
    longitude numeric(11,8),
    numero character varying(20) NOT NULL,
    restaurante_id bigint NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 29527)
-- Name: enderecos_restaurante_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enderecos_restaurante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enderecos_restaurante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 277 (class 1259 OID 30079)
-- Name: entregador_restaurante; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entregador_restaurante (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    desvinculado_em timestamp(6) without time zone,
    vinculado_em timestamp(6) without time zone NOT NULL,
    entregador_id bigint NOT NULL,
    restaurante_id bigint NOT NULL
);


--
-- TOC entry 276 (class 1259 OID 30078)
-- Name: entregador_restaurante_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entregador_restaurante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entregador_restaurante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 29536)
-- Name: entregadores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entregadores (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    atualizado_em timestamp(6) without time zone,
    avaliacao numeric(3,2),
    categoria_cnh character varying(5),
    cnh character varying(20),
    cor_veiculo character varying(50),
    cpf character varying(14) NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    disponivel boolean NOT NULL,
    email character varying(255),
    foto_cnh_url character varying(500),
    foto_perfil_url character varying(500),
    foto_veiculo_url character varying(500),
    modelo_veiculo character varying(100),
    nome_completo character varying(255) NOT NULL,
    placa_veiculo character varying(10),
    telefone character varying(20) NOT NULL,
    tipo_veiculo character varying(30),
    total_entregas integer NOT NULL,
    CONSTRAINT entregadores_categoria_cnh_check CHECK (((categoria_cnh)::text = ANY ((ARRAY['A'::character varying, 'B'::character varying, 'AB'::character varying, 'C'::character varying, 'D'::character varying, 'E'::character varying])::text[]))),
    CONSTRAINT entregadores_tipo_veiculo_check CHECK (((tipo_veiculo)::text = ANY ((ARRAY['BICICLETA'::character varying, 'MOTO'::character varying, 'CARRO'::character varying])::text[])))
);


--
-- TOC entry 229 (class 1259 OID 29535)
-- Name: entregadores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entregadores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entregadores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 29977)
-- Name: estabelecimentos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estabelecimentos (
    id_estabelecimento bigint NOT NULL,
    nome character varying(255) NOT NULL,
    telefone character varying(20),
    endereco character varying(500),
    latitude double precision,
    longitude double precision,
    ativo boolean DEFAULT true NOT NULL,
    data_cadastro timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 268 (class 1259 OID 29976)
-- Name: estabelecimentos_id_estabelecimento_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.estabelecimentos_id_estabelecimento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5361 (class 0 OID 0)
-- Dependencies: 268
-- Name: estabelecimentos_id_estabelecimento_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.estabelecimentos_id_estabelecimento_seq OWNED BY public.estabelecimentos.id_estabelecimento;


--
-- TOC entry 253 (class 1259 OID 29796)
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- TOC entry 232 (class 1259 OID 29546)
-- Name: grupos_opcoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grupos_opcoes (
    id bigint NOT NULL,
    descricao text,
    maximo_selecoes integer,
    minimo_selecoes integer,
    nome character varying(100) NOT NULL,
    obrigatorio boolean NOT NULL,
    ordem_exibicao integer,
    produto_id bigint NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 29545)
-- Name: grupos_opcoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grupos_opcoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupos_opcoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 29554)
-- Name: historico_disponibilidade_entregador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historico_disponibilidade_entregador (
    id bigint NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    disponivel boolean NOT NULL,
    latitude numeric(10,8),
    longitude numeric(11,8),
    entregador_id bigint NOT NULL
);


--
-- TOC entry 233 (class 1259 OID 29553)
-- Name: historico_disponibilidade_entregador_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.historico_disponibilidade_entregador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historico_disponibilidade_entregador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 29956)
-- Name: historico_login; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historico_login (
    id bigint NOT NULL,
    usuario_id uuid NOT NULL,
    ip_origem character varying(45),
    user_agent text,
    sucesso boolean NOT NULL,
    motivo_falha character varying(255),
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 5362 (class 0 OID 0)
-- Dependencies: 267
-- Name: TABLE historico_login; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.historico_login IS 'Histórico de tentativas de login para auditoria e segurança';


--
-- TOC entry 5363 (class 0 OID 0)
-- Dependencies: 267
-- Name: COLUMN historico_login.sucesso; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.historico_login.sucesso IS 'Se o login foi bem-sucedido';


--
-- TOC entry 5364 (class 0 OID 0)
-- Dependencies: 267
-- Name: COLUMN historico_login.motivo_falha; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.historico_login.motivo_falha IS 'Motivo da falha (credenciais inválidas, conta bloqueada, etc)';


--
-- TOC entry 266 (class 1259 OID 29955)
-- Name: historico_login_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.historico_login_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5365 (class 0 OID 0)
-- Dependencies: 266
-- Name: historico_login_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.historico_login_id_seq OWNED BY public.historico_login.id;


--
-- TOC entry 236 (class 1259 OID 29560)
-- Name: historico_status_pedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historico_status_pedido (
    id bigint NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    criado_por character varying(100),
    observacoes text,
    status character varying(30) NOT NULL,
    pedido_id bigint NOT NULL,
    CONSTRAINT historico_status_pedido_status_check CHECK (((status)::text = ANY ((ARRAY['AGUARDANDO_CONFIRMACAO'::character varying, 'PENDENTE'::character varying, 'CONFIRMADO'::character varying, 'EM_PREPARO'::character varying, 'PREPARANDO'::character varying, 'PRONTO'::character varying, 'EM_ENTREGA'::character varying, 'DESPACHADO'::character varying, 'ENTREGUE'::character varying, 'CANCELADO'::character varying])::text[])))
);


--
-- TOC entry 235 (class 1259 OID 29559)
-- Name: historico_status_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.historico_status_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historico_status_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 29569)
-- Name: horarios_restaurante; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.horarios_restaurante (
    id bigint NOT NULL,
    dia_semana integer NOT NULL,
    fechado boolean NOT NULL,
    horario_abertura time(6) without time zone NOT NULL,
    horario_fechamento time(6) without time zone NOT NULL,
    restaurante_id bigint NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 29568)
-- Name: horarios_restaurante_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.horarios_restaurante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.horarios_restaurante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 29575)
-- Name: imagens_produto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.imagens_produto (
    id bigint NOT NULL,
    altura integer,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone NOT NULL,
    imagem_base64 text,
    largura integer,
    nome_arquivo character varying(255) NOT NULL,
    ordem_exibicao integer,
    principal boolean NOT NULL,
    tamanho_bytes bigint NOT NULL,
    tipo_mime character varying(100) NOT NULL,
    url_bucket character varying(500),
    produto_id bigint NOT NULL
);


--
-- TOC entry 239 (class 1259 OID 29574)
-- Name: imagens_produto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.imagens_produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagens_produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 29583)
-- Name: itens_pedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.itens_pedido (
    id bigint NOT NULL,
    observacoes text,
    preco_unitario numeric(10,2) NOT NULL,
    quantidade integer NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    pedido_id bigint NOT NULL,
    produto_id bigint NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 29582)
-- Name: itens_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.itens_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 29591)
-- Name: opcoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.opcoes (
    id bigint NOT NULL,
    disponivel boolean NOT NULL,
    nome character varying(100) NOT NULL,
    ordem_exibicao integer,
    preco_adicional numeric(10,2),
    grupo_opcao_id bigint NOT NULL,
    qtd_fatias integer,
    max_sabores integer
);


--
-- TOC entry 243 (class 1259 OID 29590)
-- Name: opcoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.opcoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.opcoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 29597)
-- Name: opcoes_item_pedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.opcoes_item_pedido (
    id bigint NOT NULL,
    preco_adicional numeric(10,2),
    grupo_opcao_id bigint NOT NULL,
    item_pedido_id bigint NOT NULL,
    opcao_id bigint NOT NULL,
    quantidade integer DEFAULT 1
);


--
-- TOC entry 245 (class 1259 OID 29596)
-- Name: opcoes_item_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.opcoes_item_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.opcoes_item_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 281 (class 1259 OID 30159)
-- Name: pedidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedidos (
    id bigint NOT NULL,
    numero_pedido character varying(255) NOT NULL,
    data_pedido timestamp(6) without time zone NOT NULL,
    status character varying(50) NOT NULL,
    observacoes text,
    subtotal numeric(10,2) NOT NULL,
    taxa_entrega numeric(10,2),
    desconto numeric(10,2),
    valor_total numeric(10,2),
    valor_troco numeric(10,2),
    tipo_pagamento_id bigint NOT NULL,
    status_pagamento character varying(50) NOT NULL,
    cliente_id bigint NOT NULL,
    cliente_nome character varying(255),
    restaurante_id bigint,
    entregador_id bigint,
    endereco_logradouro character varying(255) NOT NULL,
    endereco_numero character varying(255) NOT NULL,
    endereco_complemento character varying(255),
    endereco_bairro character varying(255) NOT NULL,
    endereco_cidade character varying(255) NOT NULL,
    endereco_estado character varying(255) NOT NULL,
    endereco_cep character varying(255) NOT NULL,
    endereco_latitude numeric(10,8),
    endereco_longitude numeric(11,8),
    previsao_entrega timestamp(6) without time zone,
    criado_em timestamp(6) without time zone NOT NULL,
    data_atualizacao timestamp(6) without time zone,
    confirmado_em timestamp(6) without time zone,
    preparando_em timestamp(6) without time zone,
    pronto_em timestamp(6) without time zone,
    despachado_em timestamp(6) without time zone,
    entregue_em timestamp(6) without time zone,
    cancelado_em timestamp(6) without time zone,
    motivo_cancelamento text,
    rota_entrega_id bigint,
    ordem_entrega integer,
    distancia_km double precision,
    tempo_estimado_minutos integer,
    CONSTRAINT pedidos_status_check CHECK (((status)::text = ANY ((ARRAY['AGUARDANDO_CONFIRMACAO'::character varying, 'PENDENTE'::character varying, 'CONFIRMADO'::character varying, 'EM_PREPARO'::character varying, 'PREPARANDO'::character varying, 'PRONTO'::character varying, 'EM_ENTREGA'::character varying, 'DESPACHADO'::character varying, 'ENTREGUE'::character varying, 'CANCELADO'::character varying])::text[]))),
    CONSTRAINT pedidos_status_pagamento_check CHECK (((status_pagamento)::text = ANY ((ARRAY['PENDENTE'::character varying, 'PROCESSANDO'::character varying, 'APROVADO'::character varying, 'RECUSADO'::character varying, 'CANCELADO'::character varying, 'ESTORNADO'::character varying])::text[])))
);


--
-- TOC entry 280 (class 1259 OID 30158)
-- Name: pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 29825)
-- Name: perfis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.perfis (
    id bigint NOT NULL,
    nome character varying(50) NOT NULL,
    descricao text,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 5366 (class 0 OID 0)
-- Dependencies: 256
-- Name: TABLE perfis; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.perfis IS 'Perfis de acesso: SUPER_ADMIN, ADMIN, GERENTE, ATENDENTE';


--
-- TOC entry 5367 (class 0 OID 0)
-- Dependencies: 256
-- Name: COLUMN perfis.nome; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.perfis.nome IS 'Nome único do perfil (SUPER_ADMIN, ADMIN, GERENTE, ATENDENTE)';


--
-- TOC entry 255 (class 1259 OID 29824)
-- Name: perfis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.perfis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5368 (class 0 OID 0)
-- Dependencies: 255
-- Name: perfis_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.perfis_id_seq OWNED BY public.perfis.id;


--
-- TOC entry 262 (class 1259 OID 29881)
-- Name: perfis_permissoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.perfis_permissoes (
    id bigint NOT NULL,
    perfil_id bigint NOT NULL,
    permissao_id bigint NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 5369 (class 0 OID 0)
-- Dependencies: 262
-- Name: TABLE perfis_permissoes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.perfis_permissoes IS 'Relaciona perfis com permissões';


--
-- TOC entry 261 (class 1259 OID 29880)
-- Name: perfis_permissoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.perfis_permissoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5370 (class 0 OID 0)
-- Dependencies: 261
-- Name: perfis_permissoes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.perfis_permissoes_id_seq OWNED BY public.perfis_permissoes.id;


--
-- TOC entry 260 (class 1259 OID 29864)
-- Name: permissoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissoes (
    id bigint NOT NULL,
    codigo character varying(100) NOT NULL,
    nome character varying(100) NOT NULL,
    descricao text,
    modulo character varying(50) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 5371 (class 0 OID 0)
-- Dependencies: 260
-- Name: TABLE permissoes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.permissoes IS 'Permissões granulares do sistema (formato: modulo.acao)';


--
-- TOC entry 5372 (class 0 OID 0)
-- Dependencies: 260
-- Name: COLUMN permissoes.codigo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.permissoes.codigo IS 'Código único da permissão (ex: pedidos.visualizar)';


--
-- TOC entry 5373 (class 0 OID 0)
-- Dependencies: 260
-- Name: COLUMN permissoes.modulo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.permissoes.modulo IS 'Módulo ao qual a permissão pertence';


--
-- TOC entry 259 (class 1259 OID 29863)
-- Name: permissoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.permissoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5374 (class 0 OID 0)
-- Dependencies: 259
-- Name: permissoes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.permissoes_id_seq OWNED BY public.permissoes.id;


--
-- TOC entry 248 (class 1259 OID 29613)
-- Name: produtos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produtos (
    id bigint NOT NULL,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone NOT NULL,
    descricao text,
    destaque boolean NOT NULL,
    disponivel boolean NOT NULL,
    nome character varying(255) NOT NULL,
    ordem_exibicao integer,
    preco numeric(10,2) NOT NULL,
    preco_promocional numeric(10,2),
    tempo_preparo integer,
    categoria_id bigint NOT NULL,
    restaurante_id bigint NOT NULL,
    quantidade_estoque integer DEFAULT 0,
    empresa_id bigint,
    tipo character varying(20) DEFAULT 'SIMPLES'::character varying NOT NULL
);


--
-- TOC entry 293 (class 1259 OID 30301)
-- Name: produtos_combo_itens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produtos_combo_itens (
    id bigint NOT NULL,
    produto_pai_id bigint NOT NULL,
    produto_item_id bigint NOT NULL,
    quantidade integer NOT NULL,
    obrigatorio boolean DEFAULT true NOT NULL
);


--
-- TOC entry 292 (class 1259 OID 30300)
-- Name: produtos_combo_itens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.produtos_combo_itens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5375 (class 0 OID 0)
-- Dependencies: 292
-- Name: produtos_combo_itens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.produtos_combo_itens_id_seq OWNED BY public.produtos_combo_itens.id;


--
-- TOC entry 247 (class 1259 OID 29612)
-- Name: produtos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.produtos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 29902)
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id uuid NOT NULL,
    usuario_id uuid NOT NULL,
    token character varying(500) NOT NULL,
    expira_em timestamp without time zone NOT NULL,
    revogado boolean DEFAULT false NOT NULL,
    ip_origem character varying(45),
    user_agent text,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 5376 (class 0 OID 0)
-- Dependencies: 263
-- Name: TABLE refresh_tokens; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.refresh_tokens IS 'Tokens de refresh para renovação de access tokens';


--
-- TOC entry 5377 (class 0 OID 0)
-- Dependencies: 263
-- Name: COLUMN refresh_tokens.revogado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.refresh_tokens.revogado IS 'Se o token foi revogado';


--
-- TOC entry 295 (class 1259 OID 30331)
-- Name: restaurante_modulos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restaurante_modulos (
    id bigint NOT NULL,
    restaurante_id bigint NOT NULL,
    modulo character varying(50) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 294 (class 1259 OID 30330)
-- Name: restaurante_modulos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.restaurante_modulos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5378 (class 0 OID 0)
-- Dependencies: 294
-- Name: restaurante_modulos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.restaurante_modulos_id_seq OWNED BY public.restaurante_modulos.id;


--
-- TOC entry 275 (class 1259 OID 30027)
-- Name: restaurante_tipo_pagamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restaurante_tipo_pagamento (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    ordem_exibicao integer,
    vinculado_em timestamp(6) without time zone NOT NULL,
    restaurante_id bigint NOT NULL,
    tipo_pagamento_id bigint NOT NULL
);


--
-- TOC entry 274 (class 1259 OID 30026)
-- Name: restaurante_tipo_pagamento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.restaurante_tipo_pagamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurante_tipo_pagamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 29621)
-- Name: restaurantes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restaurantes (
    id bigint NOT NULL,
    aberto boolean NOT NULL,
    ativo boolean NOT NULL,
    atualizado_em timestamp(6) without time zone,
    avaliacao numeric(3,2),
    banner_url character varying(500),
    cnpj character varying(14),
    criado_em timestamp(6) without time zone NOT NULL,
    descricao text,
    email character varying(255),
    logo_url character varying(500),
    nome character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    taxa_entrega numeric(10,2),
    telefone character varying(20),
    tempo_medio_entrega integer,
    valor_minimo_pedido numeric(10,2),
    empresa_id bigint
);


--
-- TOC entry 249 (class 1259 OID 29620)
-- Name: restaurantes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.restaurantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 29988)
-- Name: rotas_entrega; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rotas_entrega (
    id_rota bigint NOT NULL,
    estabelecimento_id bigint NOT NULL,
    entregador_id bigint NOT NULL,
    status character varying(30) DEFAULT 'PENDENTE'::character varying NOT NULL,
    tempo_total_minutos integer,
    distancia_total_km double precision,
    data_criacao timestamp without time zone DEFAULT now() NOT NULL,
    data_inicio timestamp without time zone,
    data_finalizacao timestamp without time zone
);


--
-- TOC entry 270 (class 1259 OID 29987)
-- Name: rotas_entrega_id_rota_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rotas_entrega_id_rota_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5379 (class 0 OID 0)
-- Dependencies: 270
-- Name: rotas_entrega_id_rota_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rotas_entrega_id_rota_seq OWNED BY public.rotas_entrega.id_rota;


--
-- TOC entry 252 (class 1259 OID 29629)
-- Name: tipos_pagamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_pagamento (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    codigo character varying(30) NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    descricao text,
    icone_url character varying(500),
    nome character varying(100) NOT NULL,
    ordem_exibicao integer,
    requer_troco boolean NOT NULL
);


--
-- TOC entry 251 (class 1259 OID 29628)
-- Name: tipos_pagamento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tipos_pagamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipos_pagamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 29941)
-- Name: tokens_recuperacao_senha; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tokens_recuperacao_senha (
    id uuid NOT NULL,
    usuario_id uuid NOT NULL,
    code_hash character varying(255) NOT NULL,
    expira_em timestamp without time zone NOT NULL,
    usado boolean DEFAULT false NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 5380 (class 0 OID 0)
-- Dependencies: 265
-- Name: TABLE tokens_recuperacao_senha; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.tokens_recuperacao_senha IS 'Tokens para recuperação de senha (código de 6 dígitos)';


--
-- TOC entry 5381 (class 0 OID 0)
-- Dependencies: 265
-- Name: COLUMN tokens_recuperacao_senha.code_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.tokens_recuperacao_senha.code_hash IS 'Hash bcrypt do código de 6 dígitos';


--
-- TOC entry 264 (class 1259 OID 29922)
-- Name: tokens_verificacao_email; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tokens_verificacao_email (
    id uuid NOT NULL,
    usuario_id uuid NOT NULL,
    token character varying(500) NOT NULL,
    expira_em timestamp without time zone NOT NULL,
    usado boolean DEFAULT false NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 5382 (class 0 OID 0)
-- Dependencies: 264
-- Name: TABLE tokens_verificacao_email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.tokens_verificacao_email IS 'Tokens para verificação de email';


--
-- TOC entry 287 (class 1259 OID 30236)
-- Name: transacoes_carteira; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transacoes_carteira (
    id bigint NOT NULL,
    carteira_id bigint NOT NULL,
    pedido_id bigint,
    tipo character varying(20) NOT NULL,
    valor numeric(10,2) NOT NULL,
    descricao text,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 286 (class 1259 OID 30235)
-- Name: transacoes_carteira_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.transacoes_carteira_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5383 (class 0 OID 0)
-- Dependencies: 286
-- Name: transacoes_carteira_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.transacoes_carteira_id_seq OWNED BY public.transacoes_carteira.id;


--
-- TOC entry 254 (class 1259 OID 29805)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id uuid NOT NULL,
    nome_completo character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    senha_hash character varying(255) NOT NULL,
    telefone character varying(20),
    cpf character varying(14),
    email_verificado boolean DEFAULT false NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    ultimo_acesso timestamp without time zone,
    criado_em timestamp without time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp without time zone DEFAULT now() NOT NULL,
    tentativas_login_falhas integer DEFAULT 0 NOT NULL,
    bloqueado_ate timestamp without time zone
);


--
-- TOC entry 5384 (class 0 OID 0)
-- Dependencies: 254
-- Name: TABLE usuarios; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.usuarios IS 'Usuários do sistema (administradores, gerentes, atendentes)';


--
-- TOC entry 5385 (class 0 OID 0)
-- Dependencies: 254
-- Name: COLUMN usuarios.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.id IS 'UUID para melhor segurança e distribuição';


--
-- TOC entry 5386 (class 0 OID 0)
-- Dependencies: 254
-- Name: COLUMN usuarios.email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.email IS 'Email único usado para login';


--
-- TOC entry 5387 (class 0 OID 0)
-- Dependencies: 254
-- Name: COLUMN usuarios.senha_hash; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.senha_hash IS 'Hash bcrypt da senha';


--
-- TOC entry 5388 (class 0 OID 0)
-- Dependencies: 254
-- Name: COLUMN usuarios.cpf; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.cpf IS 'CPF único (apenas números)';


--
-- TOC entry 5389 (class 0 OID 0)
-- Dependencies: 254
-- Name: COLUMN usuarios.email_verificado; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.email_verificado IS 'Se o email foi verificado';


--
-- TOC entry 5390 (class 0 OID 0)
-- Dependencies: 254
-- Name: COLUMN usuarios.ativo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.ativo IS 'Se o usuário está ativo no sistema';


--
-- TOC entry 5391 (class 0 OID 0)
-- Dependencies: 254
-- Name: COLUMN usuarios.tentativas_login_falhas; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.tentativas_login_falhas IS 'Contador de tentativas de login falhas consecutivas';


--
-- TOC entry 5392 (class 0 OID 0)
-- Dependencies: 254
-- Name: COLUMN usuarios.bloqueado_ate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios.bloqueado_ate IS 'Data/hora até quando a conta está bloqueada (NULL = não bloqueada)';


--
-- TOC entry 258 (class 1259 OID 29840)
-- Name: usuarios_perfis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_perfis (
    id bigint NOT NULL,
    usuario_id uuid NOT NULL,
    perfil_id bigint NOT NULL,
    restaurante_id bigint,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 5393 (class 0 OID 0)
-- Dependencies: 258
-- Name: TABLE usuarios_perfis; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.usuarios_perfis IS 'Relacionamento multi-tenant entre usuários e perfis';


--
-- TOC entry 5394 (class 0 OID 0)
-- Dependencies: 258
-- Name: COLUMN usuarios_perfis.restaurante_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.usuarios_perfis.restaurante_id IS 'NULL = SUPER_ADMIN (acesso global), NOT NULL = acesso específico ao restaurante';


--
-- TOC entry 257 (class 1259 OID 29839)
-- Name: usuarios_perfis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.usuarios_perfis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5395 (class 0 OID 0)
-- Dependencies: 257
-- Name: usuarios_perfis_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.usuarios_perfis_id_seq OWNED BY public.usuarios_perfis.id;


--
-- TOC entry 273 (class 1259 OID 30013)
-- Name: usuarios_restaurante; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_restaurante (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone NOT NULL,
    criado_por uuid,
    role character varying(50) NOT NULL,
    usuario_id uuid NOT NULL,
    restaurante_id bigint NOT NULL,
    empresa_id bigint,
    CONSTRAINT usuarios_restaurante_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'GERENTE'::character varying, 'ATENDENTE'::character varying])::text[])))
);


--
-- TOC entry 272 (class 1259 OID 30012)
-- Name: usuarios_restaurante_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_restaurante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_restaurante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4931 (class 2604 OID 30195)
-- Name: avaliacoes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes ALTER COLUMN id SET DEFAULT nextval('public.avaliacoes_id_seq'::regclass);


--
-- TOC entry 4933 (class 2604 OID 30223)
-- Name: carteiras id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carteiras ALTER COLUMN id SET DEFAULT nextval('public.carteiras_id_seq'::regclass);


--
-- TOC entry 4927 (class 2604 OID 30138)
-- Name: descontos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.descontos ALTER COLUMN id SET DEFAULT nextval('public.descontos_id_seq'::regclass);


--
-- TOC entry 4940 (class 2604 OID 30275)
-- Name: empresa_modulos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresa_modulos ALTER COLUMN id SET DEFAULT nextval('public.empresa_modulos_id_seq'::regclass);


--
-- TOC entry 4938 (class 2604 OID 30263)
-- Name: empresas id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresas ALTER COLUMN id SET DEFAULT nextval('public.empresas_id_seq'::regclass);


--
-- TOC entry 4921 (class 2604 OID 29980)
-- Name: estabelecimentos id_estabelecimento; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estabelecimentos ALTER COLUMN id_estabelecimento SET DEFAULT nextval('public.estabelecimentos_id_estabelecimento_seq'::regclass);


--
-- TOC entry 4919 (class 2604 OID 29959)
-- Name: historico_login id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_login ALTER COLUMN id SET DEFAULT nextval('public.historico_login_id_seq'::regclass);


--
-- TOC entry 4902 (class 2604 OID 29828)
-- Name: perfis id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis ALTER COLUMN id SET DEFAULT nextval('public.perfis_id_seq'::regclass);


--
-- TOC entry 4911 (class 2604 OID 29884)
-- Name: perfis_permissoes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis_permissoes ALTER COLUMN id SET DEFAULT nextval('public.perfis_permissoes_id_seq'::regclass);


--
-- TOC entry 4908 (class 2604 OID 29867)
-- Name: permissoes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissoes ALTER COLUMN id SET DEFAULT nextval('public.permissoes_id_seq'::regclass);


--
-- TOC entry 4942 (class 2604 OID 30304)
-- Name: produtos_combo_itens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos_combo_itens ALTER COLUMN id SET DEFAULT nextval('public.produtos_combo_itens_id_seq'::regclass);


--
-- TOC entry 4944 (class 2604 OID 30334)
-- Name: restaurante_modulos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurante_modulos ALTER COLUMN id SET DEFAULT nextval('public.restaurante_modulos_id_seq'::regclass);


--
-- TOC entry 4924 (class 2604 OID 29991)
-- Name: rotas_entrega id_rota; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rotas_entrega ALTER COLUMN id_rota SET DEFAULT nextval('public.rotas_entrega_id_rota_seq'::regclass);


--
-- TOC entry 4936 (class 2604 OID 30239)
-- Name: transacoes_carteira id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transacoes_carteira ALTER COLUMN id SET DEFAULT nextval('public.transacoes_carteira_id_seq'::regclass);


--
-- TOC entry 4905 (class 2604 OID 29843)
-- Name: usuarios_perfis id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_perfis ALTER COLUMN id SET DEFAULT nextval('public.usuarios_perfis_id_seq'::regclass);


--
-- TOC entry 5133 (class 2606 OID 30201)
-- Name: avaliacoes avaliacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes
    ADD CONSTRAINT avaliacoes_pkey PRIMARY KEY (id);


--
-- TOC entry 5137 (class 2606 OID 30227)
-- Name: carteiras carteiras_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carteiras
    ADD CONSTRAINT carteiras_pkey PRIMARY KEY (id);


--
-- TOC entry 4960 (class 2606 OID 29486)
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- TOC entry 4962 (class 2606 OID 29494)
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- TOC entry 4977 (class 2606 OID 29509)
-- Name: cupons_pedido cupons_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cupons_pedido
    ADD CONSTRAINT cupons_pedido_pkey PRIMARY KEY (id);


--
-- TOC entry 4973 (class 2606 OID 29503)
-- Name: cupons cupons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cupons
    ADD CONSTRAINT cupons_pkey PRIMARY KEY (id);


--
-- TOC entry 5124 (class 2606 OID 30146)
-- Name: descontos descontos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.descontos
    ADD CONSTRAINT descontos_pkey PRIMARY KEY (id);


--
-- TOC entry 4979 (class 2606 OID 29518)
-- Name: documentos_entregador documentos_entregador_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_entregador
    ADD CONSTRAINT documentos_entregador_pkey PRIMARY KEY (id);


--
-- TOC entry 5147 (class 2606 OID 30278)
-- Name: empresa_modulos empresa_modulos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresa_modulos
    ADD CONSTRAINT empresa_modulos_pkey PRIMARY KEY (id);


--
-- TOC entry 5143 (class 2606 OID 30270)
-- Name: empresas empresas_cnpj_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT empresas_cnpj_key UNIQUE (cnpj);


--
-- TOC entry 5145 (class 2606 OID 30268)
-- Name: empresas empresas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT empresas_pkey PRIMARY KEY (id);


--
-- TOC entry 4984 (class 2606 OID 29526)
-- Name: enderecos_cliente enderecos_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enderecos_cliente
    ADD CONSTRAINT enderecos_cliente_pkey PRIMARY KEY (id);


--
-- TOC entry 4988 (class 2606 OID 29534)
-- Name: enderecos_restaurante enderecos_restaurante_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enderecos_restaurante
    ADD CONSTRAINT enderecos_restaurante_pkey PRIMARY KEY (id);


--
-- TOC entry 5118 (class 2606 OID 30083)
-- Name: entregador_restaurante entregador_restaurante_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregador_restaurante
    ADD CONSTRAINT entregador_restaurante_pkey PRIMARY KEY (id);


--
-- TOC entry 4992 (class 2606 OID 29544)
-- Name: entregadores entregadores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregadores
    ADD CONSTRAINT entregadores_pkey PRIMARY KEY (id);


--
-- TOC entry 5105 (class 2606 OID 29986)
-- Name: estabelecimentos estabelecimentos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estabelecimentos
    ADD CONSTRAINT estabelecimentos_pkey PRIMARY KEY (id_estabelecimento);


--
-- TOC entry 5039 (class 2606 OID 29803)
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- TOC entry 5008 (class 2606 OID 29552)
-- Name: grupos_opcoes grupos_opcoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_opcoes
    ADD CONSTRAINT grupos_opcoes_pkey PRIMARY KEY (id);


--
-- TOC entry 5010 (class 2606 OID 29558)
-- Name: historico_disponibilidade_entregador historico_disponibilidade_entregador_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_disponibilidade_entregador
    ADD CONSTRAINT historico_disponibilidade_entregador_pkey PRIMARY KEY (id);


--
-- TOC entry 5099 (class 2606 OID 29964)
-- Name: historico_login historico_login_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_login
    ADD CONSTRAINT historico_login_pkey PRIMARY KEY (id);


--
-- TOC entry 5015 (class 2606 OID 29567)
-- Name: historico_status_pedido historico_status_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_status_pedido
    ADD CONSTRAINT historico_status_pedido_pkey PRIMARY KEY (id);


--
-- TOC entry 5017 (class 2606 OID 29573)
-- Name: horarios_restaurante horarios_restaurante_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.horarios_restaurante
    ADD CONSTRAINT horarios_restaurante_pkey PRIMARY KEY (id);


--
-- TOC entry 5019 (class 2606 OID 29581)
-- Name: imagens_produto imagens_produto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imagens_produto
    ADD CONSTRAINT imagens_produto_pkey PRIMARY KEY (id);


--
-- TOC entry 5021 (class 2606 OID 29589)
-- Name: itens_pedido itens_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_pedido
    ADD CONSTRAINT itens_pedido_pkey PRIMARY KEY (id);


--
-- TOC entry 5025 (class 2606 OID 29601)
-- Name: opcoes_item_pedido opcoes_item_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.opcoes_item_pedido
    ADD CONSTRAINT opcoes_item_pedido_pkey PRIMARY KEY (id);


--
-- TOC entry 5023 (class 2606 OID 29595)
-- Name: opcoes opcoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.opcoes
    ADD CONSTRAINT opcoes_pkey PRIMARY KEY (id);


--
-- TOC entry 5129 (class 2606 OID 30169)
-- Name: pedidos pedidos_numero_pedido_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_numero_pedido_key UNIQUE (numero_pedido);


--
-- TOC entry 5131 (class 2606 OID 30167)
-- Name: pedidos pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id);


--
-- TOC entry 5055 (class 2606 OID 29836)
-- Name: perfis perfis_nome_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis
    ADD CONSTRAINT perfis_nome_key UNIQUE (nome);


--
-- TOC entry 5076 (class 2606 OID 29887)
-- Name: perfis_permissoes perfis_permissoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis_permissoes
    ADD CONSTRAINT perfis_permissoes_pkey PRIMARY KEY (id);


--
-- TOC entry 5057 (class 2606 OID 29834)
-- Name: perfis perfis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis
    ADD CONSTRAINT perfis_pkey PRIMARY KEY (id);


--
-- TOC entry 5070 (class 2606 OID 29875)
-- Name: permissoes permissoes_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissoes
    ADD CONSTRAINT permissoes_codigo_key UNIQUE (codigo);


--
-- TOC entry 5072 (class 2606 OID 29873)
-- Name: permissoes permissoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissoes
    ADD CONSTRAINT permissoes_pkey PRIMARY KEY (id);


--
-- TOC entry 5149 (class 2606 OID 30307)
-- Name: produtos_combo_itens produtos_combo_itens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos_combo_itens
    ADD CONSTRAINT produtos_combo_itens_pkey PRIMARY KEY (id);


--
-- TOC entry 5027 (class 2606 OID 29619)
-- Name: produtos produtos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT produtos_pkey PRIMARY KEY (id);


--
-- TOC entry 5084 (class 2606 OID 29910)
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 5086 (class 2606 OID 29912)
-- Name: refresh_tokens refresh_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);


--
-- TOC entry 5151 (class 2606 OID 30338)
-- Name: restaurante_modulos restaurante_modulos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurante_modulos
    ADD CONSTRAINT restaurante_modulos_pkey PRIMARY KEY (id);


--
-- TOC entry 5114 (class 2606 OID 30031)
-- Name: restaurante_tipo_pagamento restaurante_tipo_pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurante_tipo_pagamento
    ADD CONSTRAINT restaurante_tipo_pagamento_pkey PRIMARY KEY (id);


--
-- TOC entry 5029 (class 2606 OID 29627)
-- Name: restaurantes restaurantes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurantes
    ADD CONSTRAINT restaurantes_pkey PRIMARY KEY (id);


--
-- TOC entry 5110 (class 2606 OID 29995)
-- Name: rotas_entrega rotas_entrega_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rotas_entrega
    ADD CONSTRAINT rotas_entrega_pkey PRIMARY KEY (id_rota);


--
-- TOC entry 5035 (class 2606 OID 29635)
-- Name: tipos_pagamento tipos_pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_pagamento
    ADD CONSTRAINT tipos_pagamento_pkey PRIMARY KEY (id);


--
-- TOC entry 5097 (class 2606 OID 29947)
-- Name: tokens_recuperacao_senha tokens_recuperacao_senha_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_recuperacao_senha
    ADD CONSTRAINT tokens_recuperacao_senha_pkey PRIMARY KEY (id);


--
-- TOC entry 5091 (class 2606 OID 29930)
-- Name: tokens_verificacao_email tokens_verificacao_email_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_verificacao_email
    ADD CONSTRAINT tokens_verificacao_email_pkey PRIMARY KEY (id);


--
-- TOC entry 5093 (class 2606 OID 29932)
-- Name: tokens_verificacao_email tokens_verificacao_email_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_verificacao_email
    ADD CONSTRAINT tokens_verificacao_email_token_key UNIQUE (token);


--
-- TOC entry 5141 (class 2606 OID 30244)
-- Name: transacoes_carteira transacoes_carteira_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transacoes_carteira
    ADD CONSTRAINT transacoes_carteira_pkey PRIMARY KEY (id);


--
-- TOC entry 4967 (class 2606 OID 29642)
-- Name: clientes uk1c96wv36rk2hwui7qhjks3mvg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT uk1c96wv36rk2hwui7qhjks3mvg UNIQUE (email);


--
-- TOC entry 5116 (class 2606 OID 30033)
-- Name: restaurante_tipo_pagamento uk69f8nfk558o9nufhyjuvsrj14; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurante_tipo_pagamento
    ADD CONSTRAINT uk69f8nfk558o9nufhyjuvsrj14 UNIQUE (restaurante_id, tipo_pagamento_id);


--
-- TOC entry 4969 (class 2606 OID 29640)
-- Name: clientes uk7wflw78ibh162cmq12ii6ffly; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT uk7wflw78ibh162cmq12ii6ffly UNIQUE (cpf);


--
-- TOC entry 4990 (class 2606 OID 29653)
-- Name: enderecos_restaurante uk86vk5km68nkejhjuh20pl7vce; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enderecos_restaurante
    ADD CONSTRAINT uk86vk5km68nkejhjuh20pl7vce UNIQUE (restaurante_id);


--
-- TOC entry 5000 (class 2606 OID 29665)
-- Name: entregadores uk8uwmb1ated7g1f47kyxqa88x4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregadores
    ADD CONSTRAINT uk8uwmb1ated7g1f47kyxqa88x4 UNIQUE (email);


--
-- TOC entry 5031 (class 2606 OID 29676)
-- Name: restaurantes uk9rdmuv8pdt7wq9c8yqybnbgtp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurantes
    ADD CONSTRAINT uk9rdmuv8pdt7wq9c8yqybnbgtp UNIQUE (slug);


--
-- TOC entry 5078 (class 2606 OID 29889)
-- Name: perfis_permissoes uk_perfil_permissao; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis_permissoes
    ADD CONSTRAINT uk_perfil_permissao UNIQUE (perfil_id, permissao_id);


--
-- TOC entry 5062 (class 2606 OID 29849)
-- Name: usuarios_perfis uk_usuario_perfil_restaurante; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_perfis
    ADD CONSTRAINT uk_usuario_perfil_restaurante UNIQUE (usuario_id, perfil_id, restaurante_id);


--
-- TOC entry 5002 (class 2606 OID 29661)
-- Name: entregadores ukc22no3qdsrs7netiitnplagft; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregadores
    ADD CONSTRAINT ukc22no3qdsrs7netiitnplagft UNIQUE (cnh);


--
-- TOC entry 5037 (class 2606 OID 29678)
-- Name: tipos_pagamento ukf7bmto39f38nuhv3sy12t8fvx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_pagamento
    ADD CONSTRAINT ukf7bmto39f38nuhv3sy12t8fvx UNIQUE (codigo);


--
-- TOC entry 4975 (class 2606 OID 29646)
-- Name: cupons ukfwxbn8wj3xijqpw9x0hevuba6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cupons
    ADD CONSTRAINT ukfwxbn8wj3xijqpw9x0hevuba6 UNIQUE (codigo);


--
-- TOC entry 5004 (class 2606 OID 29663)
-- Name: entregadores ukghao026el12cg8yen7i7lr5st; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregadores
    ADD CONSTRAINT ukghao026el12cg8yen7i7lr5st UNIQUE (cpf);


--
-- TOC entry 5033 (class 2606 OID 30115)
-- Name: restaurantes ukgvxcx6ynpt5os2urf0qpiwqda; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurantes
    ADD CONSTRAINT ukgvxcx6ynpt5os2urf0qpiwqda UNIQUE (cnpj);


--
-- TOC entry 5122 (class 2606 OID 30087)
-- Name: entregador_restaurante ukhg94fmk8s0tam0amyscmhx1b5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregador_restaurante
    ADD CONSTRAINT ukhg94fmk8s0tam0amyscmhx1b5 UNIQUE (entregador_id, restaurante_id);


--
-- TOC entry 5006 (class 2606 OID 29667)
-- Name: entregadores ukmfvg2ve1xq3ugkyncwp3vmvl6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregadores
    ADD CONSTRAINT ukmfvg2ve1xq3ugkyncwp3vmvl6 UNIQUE (telefone);


--
-- TOC entry 4971 (class 2606 OID 29644)
-- Name: clientes ukn04o2sb6gpxbq0j9r2dcurbbb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT ukn04o2sb6gpxbq0j9r2dcurbbb UNIQUE (telefone);


--
-- TOC entry 5135 (class 2606 OID 30203)
-- Name: avaliacoes uq_avaliacao_pedido; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes
    ADD CONSTRAINT uq_avaliacao_pedido UNIQUE (pedido_id);


--
-- TOC entry 5139 (class 2606 OID 30229)
-- Name: carteiras uq_carteira_cliente; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carteiras
    ADD CONSTRAINT uq_carteira_cliente UNIQUE (cliente_id);


--
-- TOC entry 5047 (class 2606 OID 29819)
-- Name: usuarios usuarios_cpf_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_cpf_key UNIQUE (cpf);


--
-- TOC entry 5049 (class 2606 OID 29817)
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- TOC entry 5064 (class 2606 OID 29847)
-- Name: usuarios_perfis usuarios_perfis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_perfis
    ADD CONSTRAINT usuarios_perfis_pkey PRIMARY KEY (id);


--
-- TOC entry 5051 (class 2606 OID 29815)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 5112 (class 2606 OID 30018)
-- Name: usuarios_restaurante usuarios_restaurante_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_restaurante
    ADD CONSTRAINT usuarios_restaurante_pkey PRIMARY KEY (id);


--
-- TOC entry 5040 (class 1259 OID 29804)
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- TOC entry 4963 (class 1259 OID 29638)
-- Name: idx_clientes_cpf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clientes_cpf ON public.clientes USING btree (cpf);


--
-- TOC entry 4964 (class 1259 OID 29637)
-- Name: idx_clientes_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clientes_email ON public.clientes USING btree (email);


--
-- TOC entry 4965 (class 1259 OID 29636)
-- Name: idx_clientes_telefone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clientes_telefone ON public.clientes USING btree (telefone);


--
-- TOC entry 5125 (class 1259 OID 30154)
-- Name: idx_desconto_periodo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_desconto_periodo ON public.descontos USING btree (data_hora_inicio, data_hora_fim);


--
-- TOC entry 5126 (class 1259 OID 30152)
-- Name: idx_desconto_produto_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_desconto_produto_id ON public.descontos USING btree (produto_id);


--
-- TOC entry 5127 (class 1259 OID 30153)
-- Name: idx_desconto_vigencia; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_desconto_vigencia ON public.descontos USING btree (ativo, data_hora_inicio, data_hora_fim);


--
-- TOC entry 4980 (class 1259 OID 29647)
-- Name: idx_documentos_entregador_entregador_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_documentos_entregador_entregador_id ON public.documentos_entregador USING btree (entregador_id);


--
-- TOC entry 4981 (class 1259 OID 29648)
-- Name: idx_documentos_entregador_tipo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_documentos_entregador_tipo ON public.documentos_entregador USING btree (tipo_documento);


--
-- TOC entry 4982 (class 1259 OID 29649)
-- Name: idx_documentos_entregador_verificado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_documentos_entregador_verificado ON public.documentos_entregador USING btree (verificado);


--
-- TOC entry 4985 (class 1259 OID 29650)
-- Name: idx_enderecos_cliente_cliente_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_enderecos_cliente_cliente_id ON public.enderecos_cliente USING btree (cliente_id);


--
-- TOC entry 4986 (class 1259 OID 29651)
-- Name: idx_enderecos_cliente_cliente_padrao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_enderecos_cliente_cliente_padrao ON public.enderecos_cliente USING btree (cliente_id, padrao);


--
-- TOC entry 5119 (class 1259 OID 30084)
-- Name: idx_entregador_restaurante_entregador; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entregador_restaurante_entregador ON public.entregador_restaurante USING btree (entregador_id);


--
-- TOC entry 5120 (class 1259 OID 30085)
-- Name: idx_entregador_restaurante_restaurante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entregador_restaurante_restaurante ON public.entregador_restaurante USING btree (restaurante_id);


--
-- TOC entry 4993 (class 1259 OID 29657)
-- Name: idx_entregadores_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entregadores_ativo ON public.entregadores USING btree (ativo);


--
-- TOC entry 4994 (class 1259 OID 29659)
-- Name: idx_entregadores_ativo_disponivel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entregadores_ativo_disponivel ON public.entregadores USING btree (ativo, disponivel);


--
-- TOC entry 4995 (class 1259 OID 29656)
-- Name: idx_entregadores_cnh; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entregadores_cnh ON public.entregadores USING btree (cnh);


--
-- TOC entry 4996 (class 1259 OID 29655)
-- Name: idx_entregadores_cpf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entregadores_cpf ON public.entregadores USING btree (cpf);


--
-- TOC entry 4997 (class 1259 OID 29658)
-- Name: idx_entregadores_disponivel; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entregadores_disponivel ON public.entregadores USING btree (disponivel);


--
-- TOC entry 4998 (class 1259 OID 29654)
-- Name: idx_entregadores_telefone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entregadores_telefone ON public.entregadores USING btree (telefone);


--
-- TOC entry 5011 (class 1259 OID 29669)
-- Name: idx_historico_disponibilidade_criado_em; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_disponibilidade_criado_em ON public.historico_disponibilidade_entregador USING btree (criado_em);


--
-- TOC entry 5012 (class 1259 OID 29670)
-- Name: idx_historico_disponibilidade_entregador_criado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_disponibilidade_entregador_criado ON public.historico_disponibilidade_entregador USING btree (entregador_id, criado_em);


--
-- TOC entry 5013 (class 1259 OID 29668)
-- Name: idx_historico_disponibilidade_entregador_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_disponibilidade_entregador_id ON public.historico_disponibilidade_entregador USING btree (entregador_id);


--
-- TOC entry 5100 (class 1259 OID 29973)
-- Name: idx_historico_login_criado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_login_criado ON public.historico_login USING btree (criado_em);


--
-- TOC entry 5101 (class 1259 OID 29972)
-- Name: idx_historico_login_sucesso; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_login_sucesso ON public.historico_login USING btree (sucesso);


--
-- TOC entry 5102 (class 1259 OID 29970)
-- Name: idx_historico_login_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_login_usuario ON public.historico_login USING btree (usuario_id);


--
-- TOC entry 5103 (class 1259 OID 29971)
-- Name: idx_historico_login_usuario_criado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_login_usuario_criado ON public.historico_login USING btree (usuario_id, criado_em);


--
-- TOC entry 5052 (class 1259 OID 29838)
-- Name: idx_perfis_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_perfis_ativo ON public.perfis USING btree (ativo);


--
-- TOC entry 5053 (class 1259 OID 29837)
-- Name: idx_perfis_nome; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_perfis_nome ON public.perfis USING btree (nome);


--
-- TOC entry 5073 (class 1259 OID 29900)
-- Name: idx_perfis_permissoes_perfil; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_perfis_permissoes_perfil ON public.perfis_permissoes USING btree (perfil_id);


--
-- TOC entry 5074 (class 1259 OID 29901)
-- Name: idx_perfis_permissoes_permissao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_perfis_permissoes_permissao ON public.perfis_permissoes USING btree (permissao_id);


--
-- TOC entry 5065 (class 1259 OID 29878)
-- Name: idx_permissoes_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permissoes_ativo ON public.permissoes USING btree (ativo);


--
-- TOC entry 5066 (class 1259 OID 29876)
-- Name: idx_permissoes_codigo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permissoes_codigo ON public.permissoes USING btree (codigo);


--
-- TOC entry 5067 (class 1259 OID 29877)
-- Name: idx_permissoes_modulo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permissoes_modulo ON public.permissoes USING btree (modulo);


--
-- TOC entry 5068 (class 1259 OID 29879)
-- Name: idx_permissoes_modulo_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permissoes_modulo_ativo ON public.permissoes USING btree (modulo, ativo);


--
-- TOC entry 5079 (class 1259 OID 29921)
-- Name: idx_refresh_tokens_expira; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_expira ON public.refresh_tokens USING btree (expira_em);


--
-- TOC entry 5080 (class 1259 OID 29918)
-- Name: idx_refresh_tokens_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_token ON public.refresh_tokens USING btree (token);


--
-- TOC entry 5081 (class 1259 OID 29919)
-- Name: idx_refresh_tokens_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_usuario ON public.refresh_tokens USING btree (usuario_id);


--
-- TOC entry 5082 (class 1259 OID 29920)
-- Name: idx_refresh_tokens_usuario_revogado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_usuario_revogado ON public.refresh_tokens USING btree (usuario_id, revogado);


--
-- TOC entry 5106 (class 1259 OID 30002)
-- Name: idx_rotas_entrega_entregador; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rotas_entrega_entregador ON public.rotas_entrega USING btree (entregador_id);


--
-- TOC entry 5107 (class 1259 OID 30001)
-- Name: idx_rotas_entrega_estabelecimento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rotas_entrega_estabelecimento ON public.rotas_entrega USING btree (estabelecimento_id);


--
-- TOC entry 5108 (class 1259 OID 30003)
-- Name: idx_rotas_entrega_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rotas_entrega_status ON public.rotas_entrega USING btree (status);


--
-- TOC entry 5094 (class 1259 OID 29953)
-- Name: idx_tokens_recup_senha_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tokens_recup_senha_usuario ON public.tokens_recuperacao_senha USING btree (usuario_id);


--
-- TOC entry 5095 (class 1259 OID 29954)
-- Name: idx_tokens_recup_senha_usuario_usado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tokens_recup_senha_usuario_usado ON public.tokens_recuperacao_senha USING btree (usuario_id, usado);


--
-- TOC entry 5087 (class 1259 OID 29938)
-- Name: idx_tokens_verif_email_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tokens_verif_email_token ON public.tokens_verificacao_email USING btree (token);


--
-- TOC entry 5088 (class 1259 OID 29939)
-- Name: idx_tokens_verif_email_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tokens_verif_email_usuario ON public.tokens_verificacao_email USING btree (usuario_id);


--
-- TOC entry 5089 (class 1259 OID 29940)
-- Name: idx_tokens_verif_email_usuario_usado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tokens_verif_email_usuario_usado ON public.tokens_verificacao_email USING btree (usuario_id, usado);


--
-- TOC entry 5041 (class 1259 OID 29822)
-- Name: idx_usuarios_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_ativo ON public.usuarios USING btree (ativo);


--
-- TOC entry 5042 (class 1259 OID 29975)
-- Name: idx_usuarios_bloqueado_ate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_bloqueado_ate ON public.usuarios USING btree (bloqueado_ate) WHERE (bloqueado_ate IS NOT NULL);


--
-- TOC entry 5043 (class 1259 OID 29821)
-- Name: idx_usuarios_cpf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_cpf ON public.usuarios USING btree (cpf);


--
-- TOC entry 5044 (class 1259 OID 29820)
-- Name: idx_usuarios_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_email ON public.usuarios USING btree (email);


--
-- TOC entry 5045 (class 1259 OID 29823)
-- Name: idx_usuarios_email_ativo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_email_ativo ON public.usuarios USING btree (email, ativo);


--
-- TOC entry 5058 (class 1259 OID 29862)
-- Name: idx_usuarios_perfis_perfil_restaurante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_perfis_perfil_restaurante ON public.usuarios_perfis USING btree (perfil_id, restaurante_id);


--
-- TOC entry 5059 (class 1259 OID 29860)
-- Name: idx_usuarios_perfis_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_perfis_usuario ON public.usuarios_perfis USING btree (usuario_id);


--
-- TOC entry 5060 (class 1259 OID 29861)
-- Name: idx_usuarios_perfis_usuario_restaurante; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuarios_perfis_usuario_restaurante ON public.usuarios_perfis USING btree (usuario_id, restaurante_id);


--
-- TOC entry 5182 (class 2606 OID 30034)
-- Name: restaurante_tipo_pagamento fk1axss7cod91ivpg5jaeeqeoki; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurante_tipo_pagamento
    ADD CONSTRAINT fk1axss7cod91ivpg5jaeeqeoki FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5184 (class 2606 OID 30088)
-- Name: entregador_restaurante fk391vut5winxu2asp7k5o4pxjo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregador_restaurante
    ADD CONSTRAINT fk391vut5winxu2asp7k5o4pxjo FOREIGN KEY (entregador_id) REFERENCES public.entregadores(id);


--
-- TOC entry 5185 (class 2606 OID 30093)
-- Name: entregador_restaurante fk397xhns7rweltyi2oirecm5o5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregador_restaurante
    ADD CONSTRAINT fk397xhns7rweltyi2oirecm5o5 FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5157 (class 2606 OID 29709)
-- Name: grupos_opcoes fk3x7ad7go5yw9e2ed1e5e6alau; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_opcoes
    ADD CONSTRAINT fk3x7ad7go5yw9e2ed1e5e6alau FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- TOC entry 5160 (class 2606 OID 29729)
-- Name: imagens_produto fk4nw4eok89ljpfn7tf63asoric; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imagens_produto
    ADD CONSTRAINT fk4nw4eok89ljpfn7tf63asoric FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- TOC entry 5166 (class 2606 OID 29784)
-- Name: produtos fk8rqw0ljwdaom34jr2t46bjtrn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT fk8rqw0ljwdaom34jr2t46bjtrn FOREIGN KEY (categoria_id) REFERENCES public.categorias(id);


--
-- TOC entry 5192 (class 2606 OID 30209)
-- Name: avaliacoes fk_avaliacao_cliente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes
    ADD CONSTRAINT fk_avaliacao_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- TOC entry 5193 (class 2606 OID 30204)
-- Name: avaliacoes fk_avaliacao_pedido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes
    ADD CONSTRAINT fk_avaliacao_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id);


--
-- TOC entry 5194 (class 2606 OID 30214)
-- Name: avaliacoes fk_avaliacao_restaurante; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes
    ADD CONSTRAINT fk_avaliacao_restaurante FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5195 (class 2606 OID 30230)
-- Name: carteiras fk_carteira_cliente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carteiras
    ADD CONSTRAINT fk_carteira_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- TOC entry 5199 (class 2606 OID 30313)
-- Name: produtos_combo_itens fk_combo_produto_item; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos_combo_itens
    ADD CONSTRAINT fk_combo_produto_item FOREIGN KEY (produto_item_id) REFERENCES public.produtos(id);


--
-- TOC entry 5200 (class 2606 OID 30308)
-- Name: produtos_combo_itens fk_combo_produto_pai; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos_combo_itens
    ADD CONSTRAINT fk_combo_produto_pai FOREIGN KEY (produto_pai_id) REFERENCES public.produtos(id);


--
-- TOC entry 5186 (class 2606 OID 30147)
-- Name: descontos fk_desconto_produto; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.descontos
    ADD CONSTRAINT fk_desconto_produto FOREIGN KEY (produto_id) REFERENCES public.produtos(id) ON DELETE CASCADE;


--
-- TOC entry 5198 (class 2606 OID 30279)
-- Name: empresa_modulos fk_empresa_modulos_empresa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresa_modulos
    ADD CONSTRAINT fk_empresa_modulos_empresa FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- TOC entry 5177 (class 2606 OID 29965)
-- Name: historico_login fk_historico_login_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_login
    ADD CONSTRAINT fk_historico_login_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 5201 (class 2606 OID 30339)
-- Name: restaurante_modulos fk_modulo_restaurante; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurante_modulos
    ADD CONSTRAINT fk_modulo_restaurante FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5187 (class 2606 OID 30324)
-- Name: pedidos fk_pedido_rota; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk_pedido_rota FOREIGN KEY (rota_entrega_id) REFERENCES public.rotas_entrega(id_rota);


--
-- TOC entry 5188 (class 2606 OID 30170)
-- Name: pedidos fk_pedidos_cliente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- TOC entry 5189 (class 2606 OID 30185)
-- Name: pedidos fk_pedidos_entregador; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk_pedidos_entregador FOREIGN KEY (entregador_id) REFERENCES public.entregadores(id);


--
-- TOC entry 5190 (class 2606 OID 30175)
-- Name: pedidos fk_pedidos_restaurante; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk_pedidos_restaurante FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5191 (class 2606 OID 30180)
-- Name: pedidos fk_pedidos_tipo_pagamento; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk_pedidos_tipo_pagamento FOREIGN KEY (tipo_pagamento_id) REFERENCES public.tipos_pagamento(id);


--
-- TOC entry 5172 (class 2606 OID 29890)
-- Name: perfis_permissoes fk_perfis_permissoes_perfil; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis_permissoes
    ADD CONSTRAINT fk_perfis_permissoes_perfil FOREIGN KEY (perfil_id) REFERENCES public.perfis(id) ON DELETE CASCADE;


--
-- TOC entry 5173 (class 2606 OID 29895)
-- Name: perfis_permissoes fk_perfis_permissoes_permissao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perfis_permissoes
    ADD CONSTRAINT fk_perfis_permissoes_permissao FOREIGN KEY (permissao_id) REFERENCES public.permissoes(id) ON DELETE CASCADE;


--
-- TOC entry 5167 (class 2606 OID 30294)
-- Name: produtos fk_produtos_empresa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT fk_produtos_empresa FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- TOC entry 5174 (class 2606 OID 29913)
-- Name: refresh_tokens fk_refresh_tokens_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 5169 (class 2606 OID 30284)
-- Name: restaurantes fk_restaurantes_empresa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurantes
    ADD CONSTRAINT fk_restaurantes_empresa FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- TOC entry 5176 (class 2606 OID 29948)
-- Name: tokens_recuperacao_senha fk_tokens_recup_senha_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_recuperacao_senha
    ADD CONSTRAINT fk_tokens_recup_senha_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 5175 (class 2606 OID 29933)
-- Name: tokens_verificacao_email fk_tokens_verif_email_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_verificacao_email
    ADD CONSTRAINT fk_tokens_verif_email_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 5196 (class 2606 OID 30245)
-- Name: transacoes_carteira fk_transacao_carteira; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transacoes_carteira
    ADD CONSTRAINT fk_transacao_carteira FOREIGN KEY (carteira_id) REFERENCES public.carteiras(id);


--
-- TOC entry 5197 (class 2606 OID 30250)
-- Name: transacoes_carteira fk_transacao_pedido; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transacoes_carteira
    ADD CONSTRAINT fk_transacao_pedido FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id);


--
-- TOC entry 5179 (class 2606 OID 30344)
-- Name: usuarios_restaurante fk_usuario_restaurante_empresa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_restaurante
    ADD CONSTRAINT fk_usuario_restaurante_empresa FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- TOC entry 5170 (class 2606 OID 29855)
-- Name: usuarios_perfis fk_usuarios_perfis_perfil; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_perfis
    ADD CONSTRAINT fk_usuarios_perfis_perfil FOREIGN KEY (perfil_id) REFERENCES public.perfis(id) ON DELETE CASCADE;


--
-- TOC entry 5171 (class 2606 OID 29850)
-- Name: usuarios_perfis fk_usuarios_perfis_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_perfis
    ADD CONSTRAINT fk_usuarios_perfis_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 5180 (class 2606 OID 30289)
-- Name: usuarios_restaurante fk_usuarios_restaurante_empresa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_restaurante
    ADD CONSTRAINT fk_usuarios_restaurante_empresa FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- TOC entry 5163 (class 2606 OID 29754)
-- Name: opcoes_item_pedido fkb08yxlquh506w1vamud3ceo06; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.opcoes_item_pedido
    ADD CONSTRAINT fkb08yxlquh506w1vamud3ceo06 FOREIGN KEY (item_pedido_id) REFERENCES public.itens_pedido(id);


--
-- TOC entry 5154 (class 2606 OID 29694)
-- Name: documentos_entregador fkb3h3s2ovhai0l44fx7yknwvcs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_entregador
    ADD CONSTRAINT fkb3h3s2ovhai0l44fx7yknwvcs FOREIGN KEY (entregador_id) REFERENCES public.entregadores(id);


--
-- TOC entry 5152 (class 2606 OID 29679)
-- Name: categorias fkdqh6061saxfgyggyuo6kh2832; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT fkdqh6061saxfgyggyuo6kh2832 FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5158 (class 2606 OID 29714)
-- Name: historico_disponibilidade_entregador fke2529qxcwnunluicyw8xxpncs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_disponibilidade_entregador
    ADD CONSTRAINT fke2529qxcwnunluicyw8xxpncs FOREIGN KEY (entregador_id) REFERENCES public.entregadores(id);


--
-- TOC entry 5164 (class 2606 OID 29759)
-- Name: opcoes_item_pedido fkef93upe26upoejj6bpuy8so3h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.opcoes_item_pedido
    ADD CONSTRAINT fkef93upe26upoejj6bpuy8so3h FOREIGN KEY (opcao_id) REFERENCES public.opcoes(id);


--
-- TOC entry 5159 (class 2606 OID 29724)
-- Name: horarios_restaurante fkgai7yqnkatofge42jn009lw5s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.horarios_restaurante
    ADD CONSTRAINT fkgai7yqnkatofge42jn009lw5s FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5165 (class 2606 OID 29749)
-- Name: opcoes_item_pedido fkh5tt68utqyq7w8teee3vb56ui; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.opcoes_item_pedido
    ADD CONSTRAINT fkh5tt68utqyq7w8teee3vb56ui FOREIGN KEY (grupo_opcao_id) REFERENCES public.grupos_opcoes(id);


--
-- TOC entry 5162 (class 2606 OID 29744)
-- Name: opcoes fkkylatccf87eo2goudp1acygmx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.opcoes
    ADD CONSTRAINT fkkylatccf87eo2goudp1acygmx FOREIGN KEY (grupo_opcao_id) REFERENCES public.grupos_opcoes(id);


--
-- TOC entry 5155 (class 2606 OID 29699)
-- Name: enderecos_cliente fkl113k1u6u2y689tsxqwtp9bnt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enderecos_cliente
    ADD CONSTRAINT fkl113k1u6u2y689tsxqwtp9bnt FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- TOC entry 5153 (class 2606 OID 29684)
-- Name: cupons_pedido fkmdkj7kand6elesn3dbbvj8pkd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cupons_pedido
    ADD CONSTRAINT fkmdkj7kand6elesn3dbbvj8pkd FOREIGN KEY (cupom_id) REFERENCES public.cupons(id);


--
-- TOC entry 5183 (class 2606 OID 30039)
-- Name: restaurante_tipo_pagamento fko08sqpx2ykvql5065957en3r7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurante_tipo_pagamento
    ADD CONSTRAINT fko08sqpx2ykvql5065957en3r7 FOREIGN KEY (tipo_pagamento_id) REFERENCES public.tipos_pagamento(id);


--
-- TOC entry 5156 (class 2606 OID 29704)
-- Name: enderecos_restaurante fkocaimvmej8ifrsllleafwaxyp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enderecos_restaurante
    ADD CONSTRAINT fkocaimvmej8ifrsllleafwaxyp FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5181 (class 2606 OID 30019)
-- Name: usuarios_restaurante fkp9n8ie9w9ujbk8vrmcx9o82t8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_restaurante
    ADD CONSTRAINT fkp9n8ie9w9ujbk8vrmcx9o82t8 FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5168 (class 2606 OID 29789)
-- Name: produtos fksl3jhd8nhd103c5nm6yocnnkx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT fksl3jhd8nhd103c5nm6yocnnkx FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- TOC entry 5161 (class 2606 OID 29739)
-- Name: itens_pedido fkxytdlekpdaobqphujy9bmuhl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_pedido
    ADD CONSTRAINT fkxytdlekpdaobqphujy9bmuhl FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- TOC entry 5178 (class 2606 OID 29996)
-- Name: rotas_entrega rotas_entrega_estabelecimento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rotas_entrega
    ADD CONSTRAINT rotas_entrega_estabelecimento_id_fkey FOREIGN KEY (estabelecimento_id) REFERENCES public.estabelecimentos(id_estabelecimento);


-- Completed on 2026-03-12 20:21:51

--
-- PostgreSQL database dump complete
--

