-- SQL para recriação da tabela pedidos com a nova estrutura Embedded para endereço

CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Dados do Pedido
    numero_pedido VARCHAR(255) NOT NULL UNIQUE,
    data_pedido TIMESTAMP(6) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('AGUARDANDO_CONFIRMACAO','PENDENTE','CONFIRMADO','EM_PREPARO','PREPARANDO','PRONTO','EM_ENTREGA','DESPACHADO','ENTREGUE','CANCELADO')),
    observacoes TEXT,
    
    -- Valores Monetários
    subtotal NUMERIC(10,2) NOT NULL,
    taxa_entrega NUMERIC(10,2),
    desconto NUMERIC(10,2),
    valor_total NUMERIC(10,2),
    valor_troco NUMERIC(10,2),
    
    -- Pagamento
    tipo_pagamento_id BIGINT NOT NULL,
    status_pagamento VARCHAR(50) NOT NULL CHECK (status_pagamento IN ('PENDENTE','PROCESSANDO','APROVADO','RECUSADO','CANCELADO','ESTORNADO')),
    
    -- Relacionamentos
    cliente_id BIGINT NOT NULL,
    cliente_nome VARCHAR(255),
    restaurante_id BIGINT,
    entregador_id BIGINT,
    
    -- Endereço de Entrega (Embedded) - Novas colunas
    endereco_logradouro VARCHAR(255) NOT NULL,
    endereco_numero VARCHAR(255) NOT NULL,
    endereco_complemento VARCHAR(255),
    endereco_bairro VARCHAR(255) NOT NULL,
    endereco_cidade VARCHAR(255) NOT NULL,
    endereco_estado VARCHAR(255) NOT NULL,
    endereco_cep VARCHAR(255) NOT NULL,
    endereco_latitude NUMERIC(10,8),
    endereco_longitude NUMERIC(11,8),
    
    -- Auditoria e Timestamps
    previsao_entrega TIMESTAMP(6),
    criado_em TIMESTAMP(6) NOT NULL,
    data_atualizacao TIMESTAMP(6),
    confirmado_em TIMESTAMP(6),
    preparando_em TIMESTAMP(6),
    pronto_em TIMESTAMP(6),
    despachado_em TIMESTAMP(6),
    entregue_em TIMESTAMP(6),
    cancelado_em TIMESTAMP(6),
    motivo_cancelamento TEXT,

    -- Constraints de Chave Estrangeira
    CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_pedidos_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id),
    CONSTRAINT fk_pedidos_tipo_pagamento FOREIGN KEY (tipo_pagamento_id) REFERENCES tipos_pagamento(id),
    CONSTRAINT fk_pedidos_entregador FOREIGN KEY (entregador_id) REFERENCES entregadores(id)
);
